TARGETS = callbacks cancel check count create delete exit notify refer
EXTRA_OBJS = ../mutex/mutex-imports.o ../../modules/loadexec-imports.o
EXTRA_LIBS = -lpsppower

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
