all:
	$(MAKE) --no-print-directory -f simple.mak
	$(MAKE) --no-print-directory -f loader.mak

clean:
	$(MAKE) --no-print-directory -f simple.mak clean
	$(MAKE) --no-print-directory -f loader.mak clean

rebuild: clean all