//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.GLWidget glwidget1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = "MainWindow";
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.glwidget1 = new Gtk.GLWidget();
        this.glwidget1.Name = "glwidget1";
        this.glwidget1.SingleBuffer = false;
        this.glwidget1.ColorBPP = 0;
        this.glwidget1.AccumulatorBPP = 0;
        this.glwidget1.DepthBPP = 0;
        this.glwidget1.StencilBPP = 0;
        this.glwidget1.Samples = 0;
        this.glwidget1.Stereo = false;
        this.glwidget1.GlVersionMajor = 0;
        this.glwidget1.GlVersionMinor = 0;
        this.Add(this.glwidget1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
