//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.530
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPspEmu.Core {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSPspEmu.Core.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show &amp;Thread Info.
        /// </summary>
        public static string DebugShowThreadInfoMenu {
            get {
                return ResourceManager.GetString("DebugShowThreadInfoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trace &amp;Syscalls.
        /// </summary>
        public static string DebugTraceSyscallsMenu {
            get {
                return ResourceManager.GetString("DebugTraceSyscallsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trace Unimplemented Gpu.
        /// </summary>
        public static string DebugTraceUnimplementedGpuMenu {
            get {
                return ResourceManager.GetString("DebugTraceUnimplementedGpuMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trace Unimplemented Syscalls.
        /// </summary>
        public static string DebugTraceUnimplementedSyscallsMenu {
            get {
                return ResourceManager.GetString("DebugTraceUnimplementedSyscallsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Exit.
        /// </summary>
        public static string FileExitMenu {
            get {
                return ResourceManager.GetString("FileExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Open....
        /// </summary>
        public static string FileOpenMenu {
            get {
                return ResourceManager.GetString("FileOpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;About....
        /// </summary>
        public static string HelpAboutMenu {
            get {
                return ResourceManager.GetString("HelpAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;en.blog.cballesterosvelasco.es.
        /// </summary>
        public static string HelpBlogMenu {
            get {
                return ResourceManager.GetString("HelpBlogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check for &amp;updates....
        /// </summary>
        public static string HelpCheckForUpdatesMenu {
            get {
                return ResourceManager.GetString("HelpCheckForUpdatesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;github.com/soywiz/cspspemu.
        /// </summary>
        public static string HelpGithubMenu {
            get {
                return ResourceManager.GetString("HelpGithubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;kawagames.com.
        /// </summary>
        public static string HelpKawagamesMenu {
            get {
                return ResourceManager.GetString("HelpKawagamesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report an &amp;issue....
        /// </summary>
        public static string HelpReportAnIssueMenu {
            get {
                return ResourceManager.GetString("HelpReportAnIssueMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Website.
        /// </summary>
        public static string HelpWebsiteMenu {
            get {
                return ResourceManager.GetString("HelpWebsiteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Run.
        /// </summary>
        public static string RunMenu {
            get {
                return ResourceManager.GetString("RunMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Pause.
        /// </summary>
        public static string RunPauseMenu {
            get {
                return ResourceManager.GetString("RunPauseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Run/Resume.
        /// </summary>
        public static string RunRunResumeMenu {
            get {
                return ResourceManager.GetString("RunRunResumeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Unknown Game&gt;.
        /// </summary>
        public static string UnknownGameText {
            get {
                return ResourceManager.GetString("UnknownGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associate Extensions (.PBP, .CSO, .DAX, .ELF).
        /// </summary>
        public static string UtilsAssociateExtensionsMenu {
            get {
                return ResourceManager.GetString("UtilsAssociateExtensionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Display.
        /// </summary>
        public static string UtilsDisplayMenu {
            get {
                return ResourceManager.GetString("UtilsDisplayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dump Main Memory....
        /// </summary>
        public static string UtilsDumpMainMemoryMenu {
            get {
                return ResourceManager.GetString("UtilsDumpMainMemoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frame Limiting.
        /// </summary>
        public static string UtilsFrameLimitingMenu {
            get {
                return ResourceManager.GetString("UtilsFrameLimitingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Language.
        /// </summary>
        public static string UtilsLanguageMenu {
            get {
                return ResourceManager.GetString("UtilsLanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Utils.
        /// </summary>
        public static string UtilsMenu {
            get {
                return ResourceManager.GetString("UtilsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take Screenshot....
        /// </summary>
        public static string UtilsTakeScreenshotMenu {
            get {
                return ResourceManager.GetString("UtilsTakeScreenshotMenu", resourceCulture);
            }
        }
    }
}
