TARGETS = vector matrix prefixes colors convert gum
EXTRA_OBJS = colors_asm.S convert_asm.S vfpu_common.c
LIBS = -lGLUT -lGL -lpspvfpu -lpspgu -lpsprtc -lpspgum -lpspmath -lcommon -lc -lm

COMMON_DIR = ../../../common
include $(COMMON_DIR)/common.mk
