TARGETS = intr waits
EXTRA_OBJS = ../threads/lwmutex/lwmutex-imports.o ../display/display-imports.o ../audio/sceaudio/audio-imports.o
EXTRA_LIBS = -lpspumd

COMMON_DIR = ../../common
include $(COMMON_DIR)/common.mk
